[theme]
primaryColor = "#6750A4"
backgroundColor = "#FFFBFE"
secondaryBackgroundColor = "#F3F4F6"
textColor = "#1C1B1F"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
